# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ce9272b585aae8b646dc1e7c833ff3bb6c8ca37e88c8b21e16b03e1ae30eac6489aec14a3c0132e4b3363b5ff92ec568a2d48748eeb94e732b550b16c10305

test:
  secret_key_base: fb8af164604bcbee5bca7128b4020f106cb3e178bda3f2756edd7891359d4f873f0f86ba05ca4eff04902579e2a1bd35fbadf851d50a667bb22dbf346d2e158c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
